// export const videoList = [
//   '001_CBSE_MATH_10_04_06_2021.mp4',
//   '001_CBSE_MATH_10_04_05_2021.mp4',
//   '001_CBSE_MATH_10_04_04_2021.mp4',
//   '001_CBSE_MATH_10_04_03_2021.mp4',
//   '001_CBSE_MATH_10_04_02_2021.mp4',
//   '001_CBSE_MATH_10_04_01_2021.mp4',
//   '001_CBSE_MATH_10_03_05_2021.mp4',
//   '001_CBSE_MATH_10_03_04_2021.mp4',
//   '001_CBSE_MATH_10_03_03_2021.mp4',
//   '001_CBSE_MATH_10_03_02_2021.mp4',
//   '001_CBSE_MATH_10_03_01_2021.mp4',
//   '001_CBSE_MATH_10_02_04_2021.mp4',
//   '001_CBSE_MATH_10_02_03_2021.mp4',
//   '001_CBSE_MATH_10_02_02_2021.mp4',
//   '001_CBSE_MATH_10_02_01_2021.mp4',
//   '001_CBSE_MATH_10_01_05_2021.mp4',
//   '001_CBSE_MATH_10_01_04_2021.mp4',
//   '001_CBSE_MATH_10_01_03_2021.mp4',
//   '001_CBSE_MATH_10_01_02_2021.mp4',
//   '001_CBSE_MATH_10_01_01_2021.mp4',
// ];

export const JSONdATA = {
  "Chapter_01 - British rule and the Tribal vision of Golden Age": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+British+rule+and+the+Tribal+vision+of+Golden+Age/001_CBSE_HIS_08_04_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+British+rule+and+the+Tribal+vision+of+Golden+Age/001_CBSE_HIS_08_04_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+British+rule+and+the+Tribal+vision+of+Golden+Age/001_CBSE_HIS_08_04_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+British+rule+and+the+Tribal+vision+of+Golden+Age/001_CBSE_HIS_08_04_03_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_1/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_1/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_1/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_1/video_4/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_1/transcript_.json",
  },
  "Chapter_02 - Company Establishes its Power": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_05_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_06_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_07_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_08_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_09_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_10_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Company+Establishes+its+Power/001_CBSE_HIS_08_02_11_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_6/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_7/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_8/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_9/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_10/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/video_11/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_2/transcript_.json",
  },
  "Chapter_03 - Factory Owners, Iron Smelters and Weavers": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_05_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_06_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Factory+Owners%2C+Iron+Smelters+and+Weavers/001_CBSE_HIS_08_06_08_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_6/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/video_7/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_3/transcript_.json",
  },
  "Chapter_04 - India After Independence": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+India+After+Independence/001_CBSE_HIS_08_10_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+India+After+Independence/001_CBSE_HIS_08_10_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+India+After+Independence/001_CBSE_HIS_08_10_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+India+After+Independence/001_CBSE_HIS_08_10_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+India+After+Independence/001_CBSE_HIS_08_10_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+India+After+Independence/001_CBSE_HIS_08_10_05_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/video_6/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_4/transcript_.json",
  },
  "Chapter_05 - National Movement": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_05_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_06_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_07_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_08_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_10_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_11_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+National+Movement/001_CBSE_HIS_08_09_12_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_6/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_7/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_8/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_9/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_10/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_11/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/video_12/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_5/transcript_.json",
  },
  "Chapter_06 - Reform Movements of India": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_05_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_06_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_07_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reform+Movements+of+India/001_CBSE_HIS_08_08_08_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_6/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_7/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/video_8/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_6/transcript_.json",
  },
  "Chapter_07 - Reforming and Education the Nation": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reforming+and+Education+the+Nation/001_CBSE_HIS_08_07_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reforming+and+Education+the+Nation/001_CBSE_HIS_08_07_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reforming+and+Education+the+Nation/001_CBSE_HIS_08_07_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reforming+and+Education+the+Nation/001_CBSE_HIS_08_07_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reforming+and+Education+the+Nation/001_CBSE_HIS_08_07_05_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Reforming+and+Education+the+Nation/001_CBSE_HIS_08_07_06_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/video_6/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_7/transcript_.json",
  },
  "Chapter_08 - Revolt of 1857": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Revolt+of+1857/001_CBSE_HIS_08_05_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Revolt+of+1857/001_CBSE_HIS_08_05_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Revolt+of+1857/001_CBSE_HIS_08_05_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Revolt+of+1857/001_CBSE_HIS_08_05_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Revolt+of+1857/001_CBSE_HIS_08_05_05_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_8/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_8/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_8/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_8/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_8/video_5/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_8/transcript_.json",
  },
  "Chapter_09 - Ruling Indian Villages and Towns": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_06_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_07_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_08_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+Ruling+Indian+Villages+and+Towns/001_CBSE_HIS_08_03_09_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_6/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_7/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_8/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/video_9/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_9/transcript_.json",
  },
  "Chapter_10 - The British Rule in India": {
    videos: [
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+The+British+Rule+in+India/001_CBSE_HIS_08_01_00_2021_INT.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+The+British+Rule+in+India/001_CBSE_HIS_08_01_01_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+The+British+Rule+in+India/001_CBSE_HIS_08_01_02_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+The+British+Rule+in+India/001_CBSE_HIS_08_01_03_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+The+British+Rule+in+India/001_CBSE_HIS_08_01_04_2021.mp4",
      "https://topschool-genai.s3.ap-south-1.amazonaws.com/Grade8-RISE-History/Chapter+-+The+British+Rule+in+India/001_CBSE_HIS_08_01_05_2021.mp4",
    ],
    video_transcript: [
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/video_1/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/video_2/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/video_3/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/video_4/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/video_5/transcripts_.json",
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/video_6/transcripts_.json",
    ],
    chapter_transcript:
      "s3://ntt-videos-gen-ai-demos-v1/chapter_transcript/chapter_10/transcript_.json",
  },
};
